package com.ted.app.core;

public enum AppContextKey {
    ADDED_WORD,
    ACTIVE_QUIZ_SESSION,
    LATEST_NUM_OF_QUESTIONS,
    LATEST_POINT,
    PENDING_WORD_FROM_SEARCH,
    QUESTION_INDEX,
    QUESTION_POINT,
    QUESTION_RESULT_MESSAGE,
    QUESTION_SHOWING_RESULT,
    QUESTION_SHOWING_EXAM_OVER
}
